version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t tactless/test-ci:develop-0.0.1 .
  push:
    machine: true
    steps:
      - checkout
      - run: docker push tactless/test-ci:develop-0.0.1
